name: megaohm
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_localizations:
    sdk: flutter
  intl: any
  go_router: ^8.0.3

  megaohm_api:
    path: packages/megaohm_api
  syncfusion_flutter_charts: ^21.2.10
  syncfusion_flutter_datepicker: ^21.2.10
  envied: ^0.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
  freezed: ^2.3.5
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  envied_generator: ^0.3.0+3

flutter:
  generate: true
  uses-material-design: true
