name: megaohm_api
description: Megaohm API
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  http: ^1.0.0
  json_annotation: ^4.8.1



dev_dependencies:
  very_good_analysis: ^5.0.0+1
  freezed: ^2.3.5
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  generate: true
